/// Flutter icons EditIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EditIcon
///      fonts:
///       - asset: fonts/EditIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EditIcon {
  EditIcon._();

  static const _kFontFam = 'EditIcon';
  static const _kFontPkg = null;

  static const IconData edit_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
